Add Middle Mouse Click on LinkGroups to open all Links in new tabs
PrettyCoffee/fluidity pull request #14
Opened 2022-03-15 16:58 UTC by austinaryain

2022-03-15 17:56 UTC, PrettyCoffee commented
Can you add an entry to the changelog? (`/src/data/changelog.ts`)

Feel free to add your name there to take credit for the feature, if you want to :)

2022-03-15 18:07 UTC, austinaryain commented
> Can you add an entry to the changelog? (`/src/data/changelog.ts`)
> 
> Feel free to add your name there to take credit for the feature, if you want to :)

Done! :smile:

2022-06-21 03:03 UTC, Starttoaster commented
This looks like a pretty neat feature. Any reason it wasn't merged?

2022-06-23 06:20 UTC, PrettyCoffee commented
> This looks like a pretty neat feature. Any reason it wasn't merged?

Its not working as expected and @austinaryain didnt fix/reply to my last comment :/

2022-06-23 12:32 UTC, austinaryain commented
> > This looks like a pretty neat feature. Any reason it wasn't merged?
> 
> Its not working as expected and @austinaryain didnt fix/reply to my last comment :/

Sorry! Not sure how I missed it but the last comment I see is you suggesting I add my name to the changelog. 

I'll take another look and fix today.

2022-06-23 12:54 UTC, austinaryain commented
> > This looks like a pretty neat feature. Any reason it wasn't merged?
> 
> Its not working as expected and @austinaryain didnt fix/reply to my last comment :/

Alright am I crazy? I'm still not seeing any comments about it not working.

2022-06-23 16:40 UTC, PrettyCoffee commented
> > > This looks like a pretty neat feature. Any reason it wasn't merged?
> > 
> > 
> > Its not working as expected and @austinaryain didnt fix/reply to my last comment :/
> 
> Alright am I crazy? I'm still not seeing any comments about it not working.

Right after your "Done! 😄" ;)

![image](https://user-images.githubusercontent.com/66521452/175349977-0b1b9258-74bc-489b-8da9-8c9b19c479e4.png)


Basically:
src/Startpage/LinkContainer/LinkContainer.tsx:41
Change `linkGroups[active]` to `linkGroups[groupIndex]` and we are ready to go.

Explanation:
`active` still has the old value at this point so we want to use `groupIndex`which has the new value which we need right here.

2022-06-23 16:41 UTC, austinaryain commented
> Explanation: `active` still has the old value at this point so we want to use `groupIndex`which has the new value which we need right here.

Got it! Thanks! I think with the review still being in a "Pending" state I didn't get to see the comments?  I'll get to this later today though, I appreciate the help :)

2022-06-23 16:43 UTC, PrettyCoffee requested changes

2022-06-23 16:43 UTC, PrettyCoffee commented on src/Startpage/LinkContainer/LinkContainer.tsx
> +            linkGroups[active].links.forEach((link, index) => {
You need to use `linkGroups[groupIndex]` here instead of the `active` variable. :)

The React state gets updated later, if you middle click another group, the old index will still be used.

2022-06-23 16:44 UTC, PrettyCoffee commented
Oooooooohhh.
Welp, thank you and sorry about that, I never reviewed in Github before 😅
Good to know.

2022-06-29 19:01 UTC, austinaryain commented on src/Startpage/LinkContainer/LinkContainer.tsx
> +            linkGroups[active].links.forEach((link, index) => {
Sorry for the delay on this, but I changed it to use the groupIndex instead. Thanks for the review / help on this one :)

2022-06-29 20:41 UTC, PrettyCoffee approved these changes

2022-06-29 20:43 UTC, merged

2022-06-29 21:03 UTC, PrettyCoffee commented
The change should be deployed now, thank you for the contribution :)